apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: expense
  labels:
    app: backend
    tier: backend
    project: expense
    purpose: deployment 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
      tier: backend
      project: expense
      purpose: deployment 
  template:
    metadata:
      labels:
        app: backend
        tier: backend
        project: expense
        purpose: deployment 
    spec:
      containers:
      - name: backend
        # image: nginx:1.14.2
        image: koti0120/backend:1.0.0

---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: expense
spec:
  # type: LoadBalancer we are commenting because it doesn't need public access..
  selector:
    app: backend
    tier: backend
    purpose: deployment
  ports:
  - protocol: TCP
    port: 8080 #service port
    targetPort: 8080 #mandatory
